# nginx proxy address - http://172.17.0.1:9283

name: grocy
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  app:
    image: lscr.io/linuxserver/grocy:latest
    pull_policy: always
    container_name: grocy-app
    restart: always
    logging: *default-logging
    networks:
      - grocy
    ports:
      - "172.17.0.1:9283:80"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
      GROCY_CURRENCY: ${GROCY_CURRENCY:-USD}
      GROCY_CULTURE: ${GROCY_CULTURE:-en}
    volumes:
      - ./volumes/config/grocy:/config

networks:
  grocy:
    name: grocy
    external: false
